apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: my-app
    type: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      requests:
        memory: 256mi
        cpu: 100m
      limits:
        memory: 512mi
        cpu: 200m