apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: my-app
    type: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx
  envFrom:
  - configMapRef:
      name: app-config
  env:
  - name: APP_COLOR
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: APP_color