apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-high
  namespace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    limits.cpu: "10"
    requests.memory: 5gi
    limits.memory: 10gi