apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: my-app
    type: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx
  imagePullSecrets:
    - name: regcred