output "filename" {
  value = local_file.pet.filename
  description = "Record the value of pet ID generated by the random_pet resource"
}

output "pet-name" {
  value = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}