apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: administrator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["list", "get", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["configMap", "secret"]
  verbs: ["list", "get", "create", "update", "delete"]